/**
 * Synthetic stress test — measurement only, no thresholds.
 *
 * Runs against the fixture at trial-runs/stress-test-<N>/ (generated by
 * scripts/generate-stress-fixture.py).  The orchestrator
 * (scripts/perf-stress.sh) starts the server and this spec measures:
 *
 *   - DOM node counts (scoped and full-page) on key routes
 *   - Fetch roundtrip (quotes + codebook endpoints), median of 3
 *     — round-trip time via performance.now() around fetch(), NOT
 *     server-side latency.  Includes JS queue + network + server time
 *   - Tag filter + search DOM deltas
 *   - First paint timings via performance.getEntriesByType("paint")
 *
 * No assertions fail on measurement values — this is data collection for
 * the @tanstack/virtual (S2) before/after comparison.  The regression
 * gate (perf-gate.spec.ts) handles thresholds on the smoke fixture.
 *
 * See docs/design-perf-stress-test.md for the plan.
 */
import { test, expect, Page } from '@playwright/test';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

test.describe.configure({ mode: 'serial' });

// ── Shared state ────────────────────────────────────────────────────────

interface Results {
  project_name?: string;
  dom: Record<string, number>;
  fetch_roundtrip_ms: Record<string, number>;
  paint_ms: Record<string, number>;
  interaction_deltas: Record<string, number>;
  heap_mb: Record<string, number>;
}

const results: Results = {
  dom: {},
  fetch_roundtrip_ms: {},
  paint_ms: {},
  interaction_deltas: {},
  heap_mb: {},
};

/**
 * Sample Chromium's JS heap via `performance.memory.usedJSHeapSize`.
 * Chromium-only; returns -1 on other browsers.  Values are quantized
 * for security (~1 MB granularity) but stable enough for regression
 * tracking of heap growth vs quote count.  Native DOM memory is NOT
 * included — approximate it separately as ~200–400 bytes per DOM node.
 */
async function sampleHeapMb(page: Page): Promise<number> {
  return await page.evaluate(() => {
    const mem = (performance as unknown as {
      memory?: { usedJSHeapSize?: number };
    }).memory;
    if (!mem || typeof mem.usedJSHeapSize !== 'number') return -1;
    return Math.round((mem.usedJSHeapSize / 1024 / 1024) * 10) / 10;
  });
}

// ── Helpers ─────────────────────────────────────────────────────────────

/**
 * Copy of the perf-gate `waitForPageReady` helper — `networkidle` alone is
 * fragile on large pages where lazy effects still register after the 500ms
 * window.  Deferred mounts can easily add 20,000 nodes between
 * networkidle firing and the real settled state.
 */
async function waitForPageReady(page: Page, timeoutMs = 30_000): Promise<void> {
  await page.waitForLoadState('networkidle', { timeout: timeoutMs });
  await page.waitForFunction(
    () => {
      const root = document.querySelector('#bn-app-root');
      return !!(root && root.children.length > 0);
    },
    { timeout: timeoutMs },
  );
  // Reset stability counters so a stale reading from a prior navigation
  // can't false-stabilise the first poll on the new page.
  await page.evaluate(() => {
    const w = window as unknown as {
      __prevDomCount?: number;
      __stableCount?: number;
    };
    delete w.__prevDomCount;
    delete w.__stableCount;
  });
  // Require THREE consecutive equal 200ms polls before declaring the DOM
  // settled.  Two-poll stability (a single 200ms gap) was prone to false
  // positives at 1,500 quotes — React's concurrent scheduler can yield
  // for >200ms between render batches, and two adjacent polls can
  // happen to catch equal mid-flush counts.  Three matches raises the
  // bar to >400ms of quiescence, which in practice only happens once
  // mounting is actually done.
  await page.waitForFunction(
    () => {
      const current = document.querySelectorAll('*').length;
      const w = window as unknown as {
        __prevDomCount?: number;
        __stableCount?: number;
      };
      if (w.__prevDomCount === current) {
        w.__stableCount = (w.__stableCount ?? 0) + 1;
      } else {
        w.__stableCount = 0;
      }
      w.__prevDomCount = current;
      // 2 increments = 3 equal readings counting the first seed.
      return (w.__stableCount ?? 0) >= 2;
    },
    { timeout: timeoutMs, polling: 200 },
  );
}

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

// ── Tests ───────────────────────────────────────────────────────────────

test.beforeAll(({}, testInfo) => {
  // Trace ZIPs bundle the browser context, including `extraHTTPHeaders`
  // — our bearer token lives there.  Playwright uploads trace as a CI
  // artifact by default.  Hard-fail if anyone flips the knob in CI;
  // locally a stray `--trace=on` is your own foot, not a token leak.
  if (process.env.CI === 'true') {
    const trace = testInfo.project.use.trace;
    const safe = trace === undefined || trace === 'off';
    if (!safe) {
      throw new Error(
        `Refusing to run with trace=${JSON.stringify(trace)} under CI — ` +
          `the bearer token in extraHTTPHeaders would be captured in ` +
          `the uploaded trace archive.  Set trace: 'off' or unset CI.`,
      );
    }
  }
});

test('server identity guard — stress fixture', async ({ page, baseURL }) => {
  // `page.request` inherits `extraHTTPHeaders` from playwright.stress.config.ts
  // — no need to re-add Authorization here.  Keeping the two in sync was a
  // subtle footgun; the config is now the single source of truth.
  const res = await page.request.get(`${baseURL}/api/projects/1/info`);
  expect(res.ok()).toBe(true);
  const data = await res.json();
  // Accept any "Stress Test (N quotes)" — the orchestrator picks N.
  expect(
    /^Stress Test \(\d+ quotes?\)$/.test(data.project_name),
    `unexpected project name: ${data.project_name}`,
  ).toBe(true);
  results.project_name = data.project_name;
});

test('DOM counts — quotes page', async ({ page }) => {
  await page.goto('/report/quotes/');
  await waitForPageReady(page);

  const counts = await page.evaluate(() => {
    // `.quote-group` wraps each section/theme; `.quote-card` is one quote.
    // Scoping to `.quote-group *` excludes NavBar, sidebar, and SVG icons
    // — noise that scales with app chrome, not quote count.
    const scoped = document.querySelectorAll('.quote-group *').length;
    const cards = document.querySelectorAll('.quote-card').length;
    const total = document.querySelectorAll('*').length;
    return { scoped, cards, total };
  });

  results.dom.quotes_scoped = counts.scoped;
  results.dom.quote_cards = counts.cards;
  results.dom.quotes_total = counts.total;
  results.heap_mb.quotes = await sampleHeapMb(page);

  const paint = await page.evaluate(() => {
    const entries = performance.getEntriesByType('paint') as PerformanceEntry[];
    const out: Record<string, number> = {};
    for (const e of entries) {
      out[e.name] = Math.round(e.startTime);
    }
    return out;
  });
  if (paint['first-contentful-paint'] !== undefined) {
    results.paint_ms.quotes_fcp = paint['first-contentful-paint'];
  }
  if (paint['first-paint'] !== undefined) {
    results.paint_ms.quotes_fp = paint['first-paint'];
  }

  console.log(
    `  quotes: ${counts.cards} cards, ${counts.scoped} scoped nodes, ${counts.total} total`,
  );
});

test('DOM counts — dashboard', async ({ page }) => {
  await page.goto('/report/');
  await waitForPageReady(page);

  const counts = await page.evaluate(() => {
    const dashboard = document.querySelector(
      '[data-testid="dashboard"], .dashboard, #bn-dashboard-root, #bn-app-root',
    );
    return {
      scoped: dashboard ? dashboard.querySelectorAll('*').length : 0,
      total: document.querySelectorAll('*').length,
    };
  });

  results.dom.dashboard_scoped = counts.scoped;
  results.dom.dashboard_total = counts.total;
  results.heap_mb.dashboard = await sampleHeapMb(page);
  console.log(`  dashboard: ${counts.scoped} scoped, ${counts.total} total`);
});

test('DOM counts — transcript s1', async ({ page }) => {
  await page.goto('/report/sessions/s1');
  await waitForPageReady(page);

  const counts = await page.evaluate(() => {
    const container = document.querySelector(
      '[data-testid="transcript"], .transcript, #bn-app-root',
    );
    return {
      scoped: container ? container.querySelectorAll('*').length : 0,
      total: document.querySelectorAll('*').length,
    };
  });

  results.dom.transcript_scoped = counts.scoped;
  results.dom.transcript_total = counts.total;
  results.heap_mb.transcript = await sampleHeapMb(page);
  console.log(`  transcript s1: ${counts.scoped} scoped, ${counts.total} total`);
});

test('fetch roundtrip — quotes endpoint (median of 3)', async ({ page, baseURL }) => {
  await page.goto('/report/');
  await waitForPageReady(page);

  // Warm-up run — first call pays SQLAlchemy compile + JIT warmup costs.
  await page.evaluate(async (url: string) => {
    const token = (window as unknown as { __BRISTLENOSE_AUTH_TOKEN__?: string })
      .__BRISTLENOSE_AUTH_TOKEN__;
    await fetch(`${url}/api/projects/1/quotes`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  }, baseURL!);

  const samples: number[] = [];
  for (let i = 0; i < 3; i++) {
    const { ms, ok, status } = await page.evaluate(async (url: string) => {
      const token = (window as unknown as { __BRISTLENOSE_AUTH_TOKEN__?: string })
        .__BRISTLENOSE_AUTH_TOKEN__;
      const start = performance.now();
      const res = await fetch(`${url}/api/projects/1/quotes`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      return { ms: performance.now() - start, ok: res.ok, status: res.status };
    }, baseURL!);
    expect(ok, `quotes API returned ${status}`).toBe(true);
    samples.push(ms);
  }

  const med = median(samples);
  results.fetch_roundtrip_ms.quotes = Math.round(med * 10) / 10;
  console.log(`  /api/projects/1/quotes: ${med.toFixed(1)}ms median`);
});

test('fetch roundtrip — codebook endpoint (median of 3)', async ({ page, baseURL }) => {
  // The sidebar fans out tag groups and quote counts from this endpoint.
  // Named this way so baselines compare to "what powers the right sidebar".
  await page.goto('/report/');
  await waitForPageReady(page);

  await page.evaluate(async (url: string) => {
    const token = (window as unknown as { __BRISTLENOSE_AUTH_TOKEN__?: string })
      .__BRISTLENOSE_AUTH_TOKEN__;
    await fetch(`${url}/api/projects/1/codebook`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  }, baseURL!);

  const samples: number[] = [];
  for (let i = 0; i < 3; i++) {
    const { ms, ok, status } = await page.evaluate(async (url: string) => {
      const token = (window as unknown as { __BRISTLENOSE_AUTH_TOKEN__?: string })
        .__BRISTLENOSE_AUTH_TOKEN__;
      const start = performance.now();
      const res = await fetch(`${url}/api/projects/1/codebook`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      return { ms: performance.now() - start, ok: res.ok, status: res.status };
    }, baseURL!);
    expect(ok, `codebook API returned ${status}`).toBe(true);
    samples.push(ms);
  }

  const med = median(samples);
  results.fetch_roundtrip_ms.codebook = Math.round(med * 10) / 10;
  console.log(`  /api/projects/1/codebook: ${med.toFixed(1)}ms median`);
});

test('Interaction — search DOM delta', async ({ page }) => {
  await page.goto('/report/quotes/');
  await waitForPageReady(page);

  const before = await page.evaluate(
    () => document.querySelectorAll('*').length,
  );

  // The toolbar hides its search behind a toggle; we only measure when
  // the input is actually visible.  This is a soft metric — skipping it
  // is fine, the scale signal comes from DOM counts.
  const searchBox = page.locator(
    '[data-testid="bn-toolbar-search-input"], [data-testid="search-input"], input.search-input',
  ).first();

  if ((await searchBox.count()) === 0 || !(await searchBox.isVisible().catch(() => false))) {
    results.interaction_deltas.search_delta = -1;
    console.log('  search input not visible — skipping search delta');
    return;
  }

  await searchBox.fill('dashboard');
  await page.waitForTimeout(500); // debounce

  const after = await page.evaluate(
    () => document.querySelectorAll('*').length,
  );
  results.interaction_deltas.search_delta = after - before;
  results.interaction_deltas.search_after = after;
  console.log(`  search delta: ${after - before} (${before} → ${after})`);
});

// ── Write results ──────────────────────────────────────────────────────

test.afterAll(() => {
  const outPath =
    process.env.STRESS_RESULTS_PATH ??
    resolve(__dirname, '..', 'stress-results.json');

  const record = {
    timestamp: new Date().toISOString(),
    ...results,
  };
  writeFileSync(outPath, JSON.stringify(record, null, 2) + '\n');

  const lines = [
    '',
    '┌── Stress measurements ───────────────────────────────────┐',
    `│  Project: ${(results.project_name ?? '?').padEnd(46)}│`,
    '├──────────────────────────────────────────────────────────┤',
    ...Object.entries(results.dom).map(
      ([k, v]) => `│  dom.${k.padEnd(24)} ${String(v).padStart(8)} nodes      │`,
    ),
    ...Object.entries(results.fetch_roundtrip_ms).map(
      ([k, v]) => `│  fetch.${k.padEnd(22)} ${String(v).padStart(8)} ms         │`,
    ),
    ...Object.entries(results.paint_ms).map(
      ([k, v]) => `│  paint.${k.padEnd(22)} ${String(v).padStart(8)} ms         │`,
    ),
    ...Object.entries(results.interaction_deltas).map(
      ([k, v]) => `│  ui.${k.padEnd(25)} ${String(v).padStart(8)}            │`,
    ),
    ...Object.entries(results.heap_mb).map(
      ([k, v]) => `│  heap.${k.padEnd(23)} ${String(v).padStart(8)} MB         │`,
    ),
    '└──────────────────────────────────────────────────────────┘',
    `  Saved: ${outPath}`,
    '',
  ];
  console.log(lines.join('\n'));
});
