"""Tests for the localhost bearer token authentication middleware."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from bristlenose.server.app import create_app
from bristlenose.server.middleware import _AUTH_EXEMPT_PREFIXES, _AUTH_REQUIRED_PREFIXES

_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "smoke-test" / "input"


@pytest.fixture()
def app():
    """Create app with auth token."""
    return create_app(project_dir=_FIXTURE_DIR, dev=True, db_url="sqlite://")


@pytest.fixture()
def raw_client(app) -> TestClient:
    """TestClient WITHOUT auto-injected auth headers (bare client)."""
    return TestClient(app)


@pytest.fixture()
def token(app) -> str:
    """The auth token generated by create_app."""
    return app.state.auth_token


# ---------------------------------------------------------------------------
# Token generation
# ---------------------------------------------------------------------------


class TestTokenGeneration:
    def test_token_is_generated(self, app) -> None:
        assert hasattr(app.state, "auth_token")
        assert app.state.auth_token

    def test_token_is_string(self, app) -> None:
        assert isinstance(app.state.auth_token, str)

    def test_token_has_sufficient_length(self, app) -> None:
        # secrets.token_urlsafe(32) produces ~43 chars
        assert len(app.state.auth_token) >= 32

    def test_token_contains_only_urlsafe_chars(self, app) -> None:
        import re
        assert re.fullmatch(r"[A-Za-z0-9_-]+", app.state.auth_token)


# ---------------------------------------------------------------------------
# Middleware — authenticated requests
# ---------------------------------------------------------------------------


class TestAuthenticatedRequests:
    def test_valid_token_passes(self, raw_client: TestClient, token: str) -> None:
        resp = raw_client.get(
            "/api/projects/1/quotes",
            headers={"Authorization": f"Bearer {token}"},
        )
        assert resp.status_code == 200

    def test_valid_token_on_media(self, raw_client: TestClient, token: str) -> None:
        # Media route — even if file doesn't exist, auth should pass (404 not 401)
        resp = raw_client.get(
            "/media/nonexistent.mp4",
            headers={"Authorization": f"Bearer {token}"},
        )
        assert resp.status_code in (404, 403)  # 403 if extension blocked, 404 if not found


# ---------------------------------------------------------------------------
# Middleware — unauthenticated requests (401)
# ---------------------------------------------------------------------------


class TestUnauthenticatedRequests:
    def test_no_header_returns_401(self, raw_client: TestClient) -> None:
        resp = raw_client.get("/api/projects/1/quotes")
        assert resp.status_code == 401

    def test_wrong_token_returns_401(self, raw_client: TestClient) -> None:
        resp = raw_client.get(
            "/api/projects/1/quotes",
            headers={"Authorization": "Bearer wrong-token"},
        )
        assert resp.status_code == 401

    def test_missing_bearer_prefix_returns_401(
        self, raw_client: TestClient, token: str
    ) -> None:
        resp = raw_client.get(
            "/api/projects/1/quotes",
            headers={"Authorization": token},  # no "Bearer " prefix
        )
        assert resp.status_code == 401

    def test_401_response_body(self, raw_client: TestClient) -> None:
        resp = raw_client.get("/api/projects/1/quotes")
        assert resp.json() == {"detail": "Unauthorized"}

    def test_media_exempt_from_auth(self, raw_client: TestClient) -> None:
        """Media routes are exempt — <video>/<audio> elements can't send auth headers."""
        resp = raw_client.get("/media/test.mp4")
        # 404 (file not found), not 401 — auth is not checked
        assert resp.status_code != 401

    def test_401_on_post(self, raw_client: TestClient) -> None:
        resp = raw_client.post(
            "/api/projects/1/codebook/groups",
            json={"name": "test"},
        )
        assert resp.status_code == 401

    def test_401_on_put(self, raw_client: TestClient) -> None:
        resp = raw_client.put(
            "/api/projects/1/hidden",
            json={},
        )
        assert resp.status_code == 401


# ---------------------------------------------------------------------------
# Exempt paths
# ---------------------------------------------------------------------------


class TestExemptPaths:
    def test_health_exempt(self, raw_client: TestClient) -> None:
        resp = raw_client.get("/api/health")
        assert resp.status_code == 200

    def test_docs_exempt(self, raw_client: TestClient) -> None:
        resp = raw_client.get("/api/docs")
        # Swagger UI returns 200 or redirects
        assert resp.status_code in (200, 307)

    def test_report_exempt(self, raw_client: TestClient) -> None:
        resp = raw_client.get("/report/")
        assert resp.status_code == 200

    def test_static_exempt(self, raw_client: TestClient) -> None:
        # Static files may not exist, but should not return 401
        resp = raw_client.get("/static/nonexistent.js")
        assert resp.status_code != 401

    def test_root_exempt(self, raw_client: TestClient) -> None:
        resp = raw_client.get("/")
        assert resp.status_code != 401


# ---------------------------------------------------------------------------
# Constant coverage
# ---------------------------------------------------------------------------


class TestMiddlewareConstants:
    def test_exempt_prefixes_are_tuples(self) -> None:
        assert isinstance(_AUTH_EXEMPT_PREFIXES, tuple)

    def test_required_prefixes_include_api(self) -> None:
        assert "/api/" in _AUTH_REQUIRED_PREFIXES

    def test_media_not_in_required_prefixes(self) -> None:
        """Media exempt — <video>/<audio> can't send Authorization headers."""
        assert "/media/" not in _AUTH_REQUIRED_PREFIXES

    def test_health_is_exempt(self) -> None:
        assert "/api/health" in _AUTH_EXEMPT_PREFIXES
