<#
.SYNOPSIS
  Build the self-contained Windows x64 Bristlenose folder (and, with -Installer,
  the Inno Setup installer) from a built wheel. docs/design-winget.md.

.EXAMPLE
  .\packaging\windows\build.ps1 -Wheel dist\bristlenose-0.33.1-py3-none-any.whl -Installer
#>
param(
    [Parameter(Mandatory = $true)][string]$Wheel,
    [string]$Python = "3.12",
    [string]$Out = "build\windows",
    [switch]$Installer,
    # Only for trying a wheel from another version against this checkout.
    [switch]$AllowVersionMismatch,
    # Fast rebuilds while iterating; never for a build that will be published.
    [switch]$SkipSmoke,
    # Fill packaging\windows\winget\ for this installer (needs -Installer).
    [switch]$Manifest,
    # Where the installer will be downloaded from; a local URL for testing.
    [string]$InstallerUrl = "",
    # 1.12.0 is what winget-pkgs' tooling (Komac) emits as of Oct 2026.
    [string]$ManifestVersion = "1.12.0"
)
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function Step($msg) { Write-Host "==> $msg" }
function Run($exe, [string[]]$argv) {
    & $exe @argv
    if ($LASTEXITCODE -ne 0) { throw "$exe exited $LASTEXITCODE" }
}

$root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$Wheel = (Resolve-Path $Wheel).Path
New-Item -ItemType Directory -Force $Out | Out-Null
$Out = (Resolve-Path $Out).Path
$venv = Join-Path $Out "venv"
$py = Join-Path $venv "Scripts\python.exe"

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) { throw "uv is not on PATH" }
if ($Manifest -and -not $Installer) { throw "-Manifest needs -Installer" }

# The bundle ships exactly the released wheel (the one PyPI gets), so it must be
# the version this checkout describes; a mismatch means the wrong file was passed.
$checkoutVersion = (Select-String -Path (Join-Path $root "bristlenose\__init__.py") -Pattern '^__version__ = "([^"]+)"').Matches[0].Groups[1].Value
$wheelVersion = ([IO.Path]::GetFileName($Wheel) -split "-")[1]
if ($wheelVersion -ne $checkoutVersion -and -not $AllowVersionMismatch) {
    throw "wheel is $wheelVersion but this checkout is $checkoutVersion (pass the released wheel, or -AllowVersionMismatch to try one anyway)"
}
$commit = "unknown"
if (Get-Command git -ErrorAction SilentlyContinue) {
    $sha = (& git -C $root rev-parse --short HEAD 2>$null)
    if ($LASTEXITCODE -eq 0 -and $sha) { $commit = $sha.Trim() }
}

Step "build venv (Python $Python)"
if (Test-Path $venv) { Remove-Item -Recurse -Force $venv }
Run uv @("venv", "--python", $Python, $venv)
$wheelUrl = "file:///" + ($Wheel -replace "\\", "/")
# Pinned to the set CI tested (packaging/windows/lock.py writes it); a build
# that resolved its own dependencies would ship something nothing tested.
$constraints = Join-Path $root "packaging\windows\constraints.txt"
Run uv @("pip", "install", "--python", $py, "--constraint", $constraints,
    "bristlenose[voice] @ $wheelUrl", "pyinstaller")

# Provenance, as the Mac sidecar bakes it (bristlenose/_build.py reads it):
# written into the build venv's copy of the package, never the repo.
# -P: without it Python puts the current directory first on sys.path, so a
# build started from the checkout root imports the checkout, not the wheel.
$pkgDir = (& $py -P -c "import bristlenose, os; print(os.path.dirname(bristlenose.__file__))").Trim()
if (-not $pkgDir -or -not $pkgDir.StartsWith($venv, [StringComparison]::OrdinalIgnoreCase)) {
    throw "bristlenose resolved to '$pkgDir', not the build venv; the bundle would package the wrong copy"
}
$buildDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
Set-Content -Path (Join-Path $pkgDir "_build_info.py") -Encoding ascii -Value @(
    "# Generated by packaging/windows/build.ps1; do not edit.",
    "GIT_SHA = ""$commit""",
    "BUILD_DATE = ""$buildDate"""
)

Step "PyInstaller"
$dist = Join-Path $Out "dist"
Run $py @("-P", "-m", "PyInstaller", "--noconfirm", "--log-level", "WARN",
    "--distpath", $dist, "--workpath", (Join-Path $Out "work"),
    (Join-Path $root "packaging\windows\bristlenose-win.spec"))
$app = Join-Path $dist "bristlenose"

Step "FFmpeg"
# Pinned: a known build, verified by hash, so the installer is reproducible.
# 9.0.2 is what winget's Gyan.FFmpeg installed on both Windows test boxes.
$ffUrl = "https://github.com/GyanD/codexffmpeg/releases/download/9.0.2/ffmpeg-9.0.2-essentials_build.zip"
$ffSha = "60f467265b1e312373dbcd92200c2618a74850f98d3d078e94296bb3fa2047ba"
$ffZip = Join-Path $Out "ffmpeg-9.0.2.zip"
if (-not (Test-Path $ffZip)) { Invoke-WebRequest -Uri $ffUrl -OutFile $ffZip }
$got = (Get-FileHash $ffZip -Algorithm SHA256).Hash.ToLower()
if ($got -ne $ffSha) { Remove-Item $ffZip; throw "FFmpeg zip hash $got, expected $ffSha" }
$ffDir = Join-Path $Out "ffmpeg"
if (Test-Path $ffDir) { Remove-Item -Recurse -Force $ffDir }
Expand-Archive -Path $ffZip -DestinationPath $ffDir
$bin = Get-ChildItem -Path $ffDir -Recurse -Filter ffmpeg.exe | Select-Object -First 1
# In tools\, not beside bristlenose.exe: the app folder goes on the user PATH,
# and ours must not shadow (or be shadowed by) a user's own FFmpeg.
$tools = Join-Path $app "tools"
New-Item -ItemType Directory -Force $tools | Out-Null
Copy-Item (Join-Path $bin.DirectoryName "ffmpeg.exe") $tools
Copy-Item (Join-Path $bin.DirectoryName "ffprobe.exe") $tools
$lic = Get-ChildItem -Path $ffDir -Recurse -Filter LICENSE* | Select-Object -First 1
if ($lic) { Copy-Item $lic.FullName (Join-Path $tools "FFmpeg-LICENSE.txt") }

# Tells doctor this is the winget/installer build, so its fix text says
# "reinstall with winget", never "pip install" (doctor_fixes.INSTALL_MARKER,
# read from sys.prefix, which is _internal\ in a PyInstaller onedir build).
Set-Content -Path (Join-Path $app "_internal\.install-method") -Value "winget" -NoNewline -Encoding ascii

$size = (Get-ChildItem $app -Recurse | Measure-Object Length -Sum).Sum / 1MB
Step ("folder: {0}  ({1:N0} MB)" -f $app, $size)

if ($SkipSmoke) {
    Step "smoke: --version only (-SkipSmoke)"
    Run (Join-Path $app "bristlenose.exe") @("--version")
} else {
    Step "smoke tests"
    & (Join-Path $PSScriptRoot "smoke.ps1") -App $app
    if ($LASTEXITCODE -ne 0) { throw "smoke tests failed" }
}

if ($Installer) {
    Step "Inno Setup"
    $iscc = Get-ChildItem -ErrorAction SilentlyContinue -Path "$env:ProgramFiles\Inno Setup *\ISCC.exe",
        "${env:ProgramFiles(x86)}\Inno Setup *\ISCC.exe", "$env:LOCALAPPDATA\Programs\Inno Setup *\ISCC.exe" |
        Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
    if (-not $iscc) { throw "Inno Setup (ISCC.exe) not found" }
    $version = (& (Join-Path $app "bristlenose.exe") --version).Trim() -replace "^.*?(\d+\.\d+\.\d+).*$", '$1'
    # AppVersion becomes the Apps & Features DisplayVersion, which winget matches
    # against PackageVersion; both must be the wheel's version.
    if ($version -ne $wheelVersion) { throw "the built exe says $version but the wheel is $wheelVersion" }
    Run $iscc @("/Qp", "/DAppVersion=$version", "/DSourceDir=$app", "/DOutDir=$Out",
        (Join-Path $root "packaging\windows\bristlenose.iss"))
    $setup = Get-Item (Join-Path $Out "bristlenose-$version-setup-x64.exe")
    $setupSha = (Get-FileHash $setup.FullName -Algorithm SHA256).Hash
    Step ("installer: {0}  ({1:N0} MB)  sha256 {2}" -f $setup.FullName, ($setup.Length / 1MB), $setupSha)

    if ($Manifest) {
        if (-not $InstallerUrl) {
            $InstallerUrl = "https://github.com/cassiocassio/bristlenose/releases/download/v$version/$($setup.Name)"
        }
        $manifestDir = Join-Path $Out "winget\Bristlenose.Bristlenose\$version"
        New-Item -ItemType Directory -Force $manifestDir | Out-Null
        $values = @{
            VERSION          = $version
            MANIFEST_VERSION = $ManifestVersion
            INSTALLER_URL    = $InstallerUrl
            INSTALLER_SHA256 = $setupSha
            RELEASE_DATE     = (Get-Date -Format "yyyy-MM-dd")
        }
        foreach ($template in Get-ChildItem (Join-Path $root "packaging\windows\winget") -Filter *.yaml) {
            $text = [IO.File]::ReadAllText($template.FullName)
            foreach ($key in $values.Keys) { $text = $text.Replace('${' + $key + '}', $values[$key]) }
            if ($text -match '\$\{[A-Z_0-9]+\}') { throw "$($template.Name): unfilled $($Matches[0])" }
            [IO.File]::WriteAllText((Join-Path $manifestDir $template.Name), $text, (New-Object Text.UTF8Encoding $false))
        }
        Step "manifest: $manifestDir"
        if (Get-Command winget -ErrorAction SilentlyContinue) { Run winget @("validate", "--manifest", $manifestDir) }
    }
}
