"""Regenerate packaging/windows/constraints.txt, the pinned dependency set the
Windows installer build installs (docs/design-winget.md, step 1.2).

A build that resolves its own dependencies at release time ships something no
test ran against (the Mac sidecar's 0.30.0 #5). So the Windows build installs
with `--constraint constraints.txt`, and the file records a digest of the
dependency lists it was compiled from; tests/test_windows_packaging.py fails
when pyproject.toml's dependencies change and this was not re-run.

    python packaging/windows/lock.py          # needs uv on PATH
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).with_name("constraints.txt")
PYPROJECT = ROOT / "pyproject.toml"
# What the build venv holds besides bristlenose[voice]. Bump deliberately.
BUILD_TOOLS = ["pyinstaller>=6.22,<7"]
PYTHON = "3.12"
PLATFORM = "x86_64-pc-windows-msvc"
DIGEST_PREFIX = "# inputs-sha256: "


def _load_toml(text: str) -> dict:
    try:
        import tomllib
    except ModuleNotFoundError:  # Python 3.10
        import tomli as tomllib  # type: ignore[no-redef]
    return tomllib.loads(text)


def inputs_digest(pyproject_text: str | None = None) -> str:
    """SHA-256 over everything the compiled set depends on."""
    if pyproject_text is None:
        pyproject_text = PYPROJECT.read_text(encoding="utf-8")
    project = _load_toml(pyproject_text)["project"]
    lines = [
        *project["dependencies"],
        *project["optional-dependencies"]["voice"],
        *BUILD_TOOLS,
        f"python={PYTHON}",
        f"platform={PLATFORM}",
    ]
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()


def recorded_digest(constraints_text: str) -> str | None:
    for line in constraints_text.splitlines():
        if line.startswith(DIGEST_PREFIX):
            return line[len(DIGEST_PREFIX):].strip()
    return None


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        build_in = Path(tmp) / "build.in"
        build_in.write_text("\n".join(BUILD_TOOLS) + "\n", encoding="utf-8")
        compiled = Path(tmp) / "out.txt"
        cmd = [
            "uv", "pip", "compile", str(PYPROJECT), str(build_in),
            "--extra", "voice",
            "--python-version", PYTHON,
            "--python-platform", PLATFORM,
            "--no-header", "--no-annotate",
            "-o", str(compiled),
        ]
        result = subprocess.run(cmd, cwd=ROOT)
        if result.returncode != 0:
            return result.returncode
        body = compiled.read_text(encoding="utf-8")
    header = (
        "# Pinned dependencies for the Windows installer build.\n"
        "# Generated by packaging/windows/lock.py; do not edit by hand.\n"
        f"# Python {PYTHON}, {PLATFORM}; bristlenose[voice] plus {', '.join(BUILD_TOOLS)}.\n"
        f"{DIGEST_PREFIX}{inputs_digest()}\n"
    )
    OUT.write_text(header + body, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
