#!/usr/bin/env bash
# Generate Swift constants for the in-app Build Info diagnostic.
#
# Reads git state + a few Xcode build-setting env vars and writes
# `desktop/Bristlenose/Bristlenose/GeneratedBuildInfo.swift`. The file is
# gitignored — it's regenerated on every build by an Xcode Run Script
# Build Phase that runs before Compile Sources.
#
# Why a generated Swift file (not Info.plist preprocessing): keeps the
# Info.plist generation path untouched and gives us strongly-typed
# constants in `BuildInfo.swift` with no runtime parsing.
#
# Inputs (Xcode env, all optional — the script falls back gracefully):
#   CONFIGURATION              "Debug" / "Release"
#   ENABLE_APP_SANDBOX         "YES" / "NO"
#   ENABLE_HARDENED_RUNTIME    "YES" / "NO"
#   SRCROOT                    used to locate the .swift output and the repo
#
# Outputs:
#   $SRCROOT/Bristlenose/GeneratedBuildInfo.swift  (when invoked from Xcode)
#   else: desktop/Bristlenose/Bristlenose/GeneratedBuildInfo.swift relative to repo
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -n "${SRCROOT:-}" ]; then
    OUTPUT="$SRCROOT/Bristlenose/GeneratedBuildInfo.swift"
else
    OUTPUT="$REPO_ROOT/desktop/Bristlenose/Bristlenose/GeneratedBuildInfo.swift"
fi

# Git data — fall back to placeholders when not in a repo or git missing.
cd "$REPO_ROOT"
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
if git diff-index --quiet HEAD -- 2>/dev/null; then
    GIT_DIRTY="false"
else
    GIT_DIRTY="true"
fi

CONFIGURATION="${CONFIGURATION:-Debug}"
SANDBOX="false"
[ "${ENABLE_APP_SANDBOX:-NO}" = "YES" ] && SANDBOX="true"
HARDENED="false"
[ "${ENABLE_HARDENED_RUNTIME:-NO}" = "YES" ] && HARDENED="true"

BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Escape any embedded double-quotes in the branch name (defensive — branch
# names can technically contain odd chars).
GIT_BRANCH_ESC="${GIT_BRANCH//\"/\\\"}"

mkdir -p "$(dirname "$OUTPUT")"

# Atomic write — only touch the file when contents actually change. Prevents
# Xcode from invalidating the Compile Sources step on every build.
TMP="$OUTPUT.tmp"
cat > "$TMP" <<EOF
// Generated by desktop/scripts/generate-build-info.sh — do not edit.
// Regenerated by Xcode Run Script Build Phase before every compile.
import Foundation

enum GeneratedBuildInfo {
    static let gitBranch = "$GIT_BRANCH_ESC"
    static let gitSHA = "$GIT_SHA"
    static let gitDirty = $GIT_DIRTY
    static let configuration = "$CONFIGURATION"
    static let sandboxEnabled = $SANDBOX
    static let hardenedRuntimeEnabled = $HARDENED
    static let buildDate = "$BUILD_DATE"
}
EOF

if [ -f "$OUTPUT" ] && cmp -s "$TMP" "$OUTPUT"; then
    rm "$TMP"
else
    mv "$TMP" "$OUTPUT"
fi
