#!/usr/bin/env bash
# Single source of truth for the "what does the sidecar serve" fingerprint.
#
# Sourced by build-sidecar.sh (which writes the stamp into the bundle) and by
# check-sidecar-freshness.sh (which recomputes + compares at Xcode-build time).
# Keeping the recipe in one place means the writer and the checker cannot drift
# — drift between them would silently defeat the gate.
#
# SHA-256 over everything that determines what the sidecar SERVES, hashed with
# paths RELATIVE to the repo root (via `cd`), so the fingerprint is content-only
# and stable across worktrees with identical source. Three input sets:
#   1. bristlenose/**/*.py    — the Python the sidecar runs
#   2. bristlenose/locales/** — i18n JSON, bundled into the SPA via the @locales
#                               Vite alias AND read at runtime
#   3. frontend/ build inputs — src/ (minus tests), index.html, the Vite/TS
#                               config, package(-lock).json. These build into
#                               bristlenose/server/static/ (gitignored, NOT
#                               produced by PyInstaller). build-sidecar.sh runs
#                               `npm run build` so the bundled static/ matches
#                               them; a missed frontend build is caught here
#                               because this hash moves when frontend src does.
#   4. the PyInstaller spec    — desktop/bristlenose-sidecar.spec is the recipe
#                               for WHAT gets packaged (datas/binaries/hidden-
#                               imports). A spec-only edit changes bundle
#                               contents without touching any .py, so without
#                               this input the P-layer gate would skip the
#                               rebuild and re-ship the stale bundle. (Added
#                               14 Jul 2026 after a `collect_all("sqladmin")`
#                               fix silently didn't rebuild on Cmd+R.)
#   5. desktop/mcpb/           — the agent extension (manifest + proxy JS).
#                               The .mcpb will ship inside Resources; an
#                               edited proxy must trip the freshness gate or
#                               a stale extension re-ships silently (design
#                               docs/design-mcp-extension.md §4, review
#                               Finding 26). Added 31 Jul 2026.
# Test files are excluded — they don't change the shipped bundle, so editing one
# must not force a sidecar rebuild. OS metadata (.DS_Store, AppleDouble ._*) is
# ALSO excluded — Finder touching a hashed dir must not drift the fingerprint
# (it did: a locales/.DS_Store made every build read "stale"; fixed 29 Jun 2026).
# bristlenose/_build_info.py is excluded for the same reason: it is GENERATED by
# build-sidecar.sh (git SHA + build date), not an input to it, and it sits on
# disk from the PyInstaller step until that script's EXIT trap removes it. If it
# counted, (a) the end-of-build race gate would differ from the entry hash on
# every single build, and (b) a copy left behind by a killed build would read as
# a source change. Excluding it is a no-op in the steady state (the file is
# absent), so it does not move anyone's fingerprint. Added 4 Aug 2026.
#
# Deterministic: paths are sorted before hashing, under `LC_ALL=C` so the
# byte-ordering is locale-independent (a locale-sensitive `sort` made the writer
# and checker disagree — caught 28 Jun 2026). bash 3.2-compatible (Xcode's
# default /bin/bash); BSD find/sort/xargs (-print0 / -z / -0).
#
# Usage:  source sidecar-source-hash.sh; h="$(sidecar_source_hash "$REPO_ROOT")"
sidecar_source_hash() {
    ( cd "$1" && {
        find bristlenose -name '*.py' -type f \
            -not -name '_build_info.py' -print0
        find bristlenose/locales -type f \
            -not -name '.DS_Store' -not -name '._*' -print0
        # The theme. NOT covered by the *.py sweep above — these are CSS/HTML
        # data files, and their absence made this a FALSE-GREEN gate: a
        # theme-only edit never moved the hash, so `check-sidecar-freshness.sh`
        # reported "✓ matches source", Xcode's Ensure Sidecar Fresh phase
        # skipped the rebuild, and the .app went on serving the previous
        # stylesheet. Worse than an absent gate, because it answers the
        # question confidently and wrongly — cost a rebuild-and-recheck cycle
        # on 5 Aug 2026 chasing a Focus Mode keyline that was already fixed in
        # source. The theme is bundled via the spec's datas and IS runtime
        # input, so it belongs in the fingerprint exactly like locales do.
        find bristlenose/theme -type f \
            -not -name '.DS_Store' -not -name '._*' -print0
        _frontend_inputs_print0
        find desktop/bristlenose-sidecar.spec -type f -print0
        find desktop/mcpb -type f \
            -not -name '.DS_Store' -not -name '._*' -print0
      } | LC_ALL=C sort -z | xargs -0 shasum -a 256 ) | shasum -a 256 | cut -d ' ' -f1
}

# The frontend slice ONLY — the inputs that build into bristlenose/server/static/.
# Same recipe, sliced (one source of truth, per the single-fingerprint rationale
# above), so the per-layer F gate in build-sidecar.sh can decide "did the frontend
# move?" without re-resolving the Python half. Stays a strict subset of
# sidecar_source_hash's inputs.
frontend_source_hash() {
    ( cd "$1" && _frontend_inputs_print0 \
      | LC_ALL=C sort -z | xargs -0 shasum -a 256 ) | shasum -a 256 | cut -d ' ' -f1
}

# Shared find recipe for the frontend build inputs. NUL-delimited; callers pipe
# through `sort -z | xargs -0 shasum`. Defined once so the full-hash and the
# frontend-slice can never disagree on what "the frontend inputs" are.
_frontend_inputs_print0() {
    find frontend/src -type f \
        -not -name '*.test.ts' -not -name '*.test.tsx' \
        -not -name '*.test.js' -not -path '*/__tests__/*' \
        -not -name '.DS_Store' -not -name '._*' -print0
    find frontend/index.html frontend/vite.config.ts frontend/tsconfig.json \
        frontend/package.json frontend/package-lock.json -type f -print0
}
