export { AboutSection } from "./AboutSection";
export { HelpSection } from "./HelpSection";
export { ShortcutsSection } from "./ShortcutsSection";
export { SignalsSection } from "./SignalsSection";
export { CodebookSection } from "./CodebookSection";
export { PrivacySection } from "./PrivacySection";
export { DeveloperSection } from "./DeveloperSection";
export { DesignSection } from "./DesignSection";
export { ContributingSection } from "./ContributingSection";
export { AcknowledgementsSection } from "./AcknowledgementsSection";
export type { DevInfoResponse, DesignSectionData } from "./types";
