"""People file (participant registry): read, compute, merge, write.

The people file (``people.yaml``) lives in the output directory and tracks
every participant across pipeline runs.  Computed stats are refreshed on
each run; human-editable fields (name, role, persona, notes) are preserved.

**Route C Phase 1 (``docs/design-people.md`` §H H9): the serve database no
longer takes moderators or observers from this file.** Identities and the
per-session moderator map live in the project database (migration 013,
``server/speaker_slots.py``), built from ``session-speakers.json`` below, which
this module writes. Participants are still named from ``people.yaml``; the file
is retired as a store in Phase 5, with the docs that promise an editable file.
The CLI's markdown report and the sealed static HTML still read it, ``m1``
collision and all.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from bristlenose.models import (
    PLATFORM_TRANSCRIPT_SOURCES,
    FullTranscript,
    InputSession,
    PeopleFile,
    PersonComputed,
    PersonEditable,
    PersonEntry,
    SpeakerRole,
)

if TYPE_CHECKING:
    from bristlenose.stages.s05b_identify_speakers import SpeakerInfo

logger = logging.getLogger(__name__)

PEOPLE_FILENAME = "people.yaml"

# ---------------------------------------------------------------------------
# Name-handling data (used by suggest_short_names)
# ---------------------------------------------------------------------------
#
# Honorific prefixes and family-first surnames are loaded from text files in
# bristlenose/data/.  See those files for sources, provenance, and how to
# expand them.

_DATA_DIR = Path(__file__).resolve().parent / "data"


def _load_data_file(filename: str) -> frozenset[str]:
    """Load a newline-delimited data file from ``bristlenose/data/``.

    Blank lines and lines starting with ``#`` are ignored.
    """
    path = _DATA_DIR / filename
    entries: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            entries.add(stripped)
    return frozenset(entries)


_HONORIFIC_PREFIXES: frozenset[str] = _load_data_file("honorifics.txt")
_FAMILY_FIRST_SURNAMES: frozenset[str] = _load_data_file("family_first_surnames.txt")

# Regex matching CJK Unified Ideographs, CJK Extension A, and Hangul
# Syllables.  Names containing these characters are already short enough to
# use as-is — we skip the "first token" heuristic entirely.
_CJK_RE = re.compile(r"[\u4e00-\u9fff\u3400-\u4dbf\uac00-\ud7af]")


def _strip_honorific(name: str) -> str:
    """Strip a leading honorific prefix from *name*.

    Returns the remainder of the name with the honorific removed, or the
    original name if no honorific is found.  Handles trailing periods on
    the prefix token (e.g. "Dr." → "Dr" → lookup).

    >>> _strip_honorific("Dr. Sarah Jones")
    'Sarah Jones'
    >>> _strip_honorific("Sarah Jones")
    'Sarah Jones'
    """
    parts = name.split(None, 1)
    if len(parts) < 2:
        return name
    token = parts[0].rstrip(".").lower()
    if token in _HONORIFIC_PREFIXES:
        return parts[1]
    return name

_HEADER = (
    "# people.yaml — participant registry (auto-generated by bristlenose)\n"
    "#\n"
    "# Computed fields are refreshed on each pipeline run.\n"
    "# Human-editable fields (full_name, short_name, role, persona, notes)\n"
    "# are preserved across runs — edit them freely.\n"
    "#\n"
    "# Set short_name to change how a participant appears in reports:\n"
    '#   short_name: Sarah  →  quotes render as "— Sarah" instead of "— p1"\n'
    "#\n"
    "# Note: inline YAML comments are lost when the file is rewritten.\n"
    "\n"
)


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------


def load_people_file(output_dir: Path) -> PeopleFile | None:
    """Load an existing ``people.yaml`` from *output_dir*.

    Returns ``None`` if the file does not exist or is empty.
    """
    path = output_dir / PEOPLE_FILENAME
    if not path.exists():
        return None
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if raw is None:
        return None
    return PeopleFile.model_validate(raw)


# ---------------------------------------------------------------------------
# Compute
# ---------------------------------------------------------------------------


def compute_participant_stats(
    sessions: list[InputSession],
    transcripts: list[FullTranscript],
) -> dict[str, PersonComputed]:
    """Compute per-participant stats from session and transcript data.

    Returns a dict keyed by ``participant_id``.

    **Known limitation — moderator/observer codes collide across sessions.**
    Participant codes are globally numbered, but ``assign_speaker_codes()``
    resets its moderator/observer counters per session, so every session's
    first moderator is ``m1``.  This dict is keyed by code alone, so in a
    multi-session study the last session's ``m1`` overwrites the earlier ones
    and only one survives into ``people.yaml``.  Collisions are collected and
    reported in a single WARNING rather than passing silently.

    The fix is **not** a ``(session, code)`` rekey of this file — that was
    considered and rejected (``docs/design-transcript-speaker-editing-roadmap.md``
    §11c, 25 Aug 2026).  Decided 1 Oct 2026: a session's moderator slot lives
    on ``session_speakers`` and is ``null`` until a platform label proposes an
    identity or a researcher picks one; the per-session ``m1`` token stays as a
    within-session tag, and this file is retired as a store.  See
    ``docs/design-people.md`` §E decision 1 (corrected) and §H H9.  Phase 1
    built the slot map in the serve database, fed by ``session_speaker_stats``
    and ``session_speaker_names``; this file keeps the limitation until Phase
    5 retires it, and
    ``tests/test_people.py::test_multi_session_moderator_codes_collide_and_are_warned``
    pins the limitation, not a desired end state.
    """
    transcript_map: dict[str, FullTranscript] = {
        t.session_id: t for t in transcripts
    }

    stats: dict[str, PersonComputed] = {}
    total_words_all = 0
    # Speaker codes seen in more than one session — see the collision note below.
    code_sessions: dict[str, list[str]] = {}

    for session in sessions:
        sid = session.session_id
        transcript = transcript_map.get(sid)

        if transcript is None:
            # No transcript — create a placeholder for the primary participant
            pid = session.participant_id
            stats[pid] = PersonComputed(
                participant_id=pid,
                session_id=sid,
                session_date=session.session_date,
                duration_seconds=0.0,
                words_spoken=0,
                pct_words=0.0,
                pct_time_speaking=0.0,
                source_file=session.files[0].path.name if session.files else "",
            )
            continue

        # Group ALL segments by speaker_code, creating per-code entries
        code_words: dict[str, int] = {}
        code_seconds: dict[str, float] = {}
        for seg in transcript.segments:
            code = seg.speaker_code or session.participant_id
            if code not in code_words:
                code_words[code] = 0
                code_seconds[code] = 0.0
            code_words[code] += len(seg.text.split())
            code_seconds[code] += max(0.0, seg.end_time - seg.start_time)

        for code, words in code_words.items():
            if code.startswith("p"):
                total_words_all += words
            # Speaker code reused across sessions — the earlier entry is about
            # to be overwritten and its stats lost.  Collected here, reported
            # once after the loop so a 10-session study doesn't print nine
            # near-identical warnings at the researcher.  See the docstring:
            # only codes that reset per session (m/o) reach this in practice.
            prior = stats.get(code)
            if prior is not None and prior.session_id != sid:
                seen = code_sessions.setdefault(code, [prior.session_id])
                seen.append(sid)
            stats[code] = PersonComputed(
                participant_id=code,
                session_id=sid,
                session_date=transcript.session_date,
                duration_seconds=transcript.duration_seconds,
                words_spoken=words,
                pct_words=0.0,  # filled in second pass
                pct_time_speaking=(
                    round(code_seconds[code] / transcript.duration_seconds * 100, 1)
                    if transcript.duration_seconds > 0
                    else 0.0
                ),
                source_file=transcript.source_file,
            )

    if code_sessions:
        detail = "; ".join(
            f"{code} in {', '.join(sids)} (only {sids[-1]} survives)"
            for code, sids in sorted(code_sessions.items())
        )
        logger.warning(
            "Speaker code reused across sessions: %s. people.yaml holds one entry "
            "per code, so the earlier sessions' stats are discarded and one name "
            "covers every session that carries the code. Moderator and observer "
            "codes restart at 1 each session; per-session moderator identity is "
            "built in the serve database (route C Phase 1), not in this file — see "
            "docs/design-people.md §H H9.",
            detail,
        )

    # Second pass: compute pct_words relative to total across all participants.
    # Only count participant codes (pN) for the denominator.
    if total_words_all > 0:
        for computed in stats.values():
            if computed.participant_id.startswith("p"):
                computed.pct_words = round(
                    computed.words_spoken / total_words_all * 100, 1
                )

    return stats


# ---------------------------------------------------------------------------
# Merge
# ---------------------------------------------------------------------------


def merge_people(
    existing: PeopleFile | None,
    computed: dict[str, PersonComputed],
) -> PeopleFile:
    """Merge new computed stats with existing human-edited fields.

    Strategy:

    * **Computed fields** are always overwritten with fresh data.
    * **Editable fields** are always preserved from the previous file.
    * New participants are added with empty editable defaults.
    * Participants present in the old file but absent from the current run
      are **kept** (the user may still want their notes).

    Preserving editable fields *by key* is correct for a code that names one
    person and is what spreads a typed moderator name to every session that
    shares the code (storyboard frame F10): a name typed for session 9's ``m1``
    is kept against stats that are now session 13's.  Route C removes the
    shared key rather than this rule — see the module docstring.
    """
    people = PeopleFile(last_updated=datetime.now(tz=timezone.utc))

    # Start with existing entries to preserve removed-but-noted participants.
    if existing:
        for pid, entry in existing.participants.items():
            people.participants[pid] = entry

    # Update / add computed stats.
    for pid, comp in computed.items():
        if pid in people.participants:
            # Preserve editable, replace computed.
            people.participants[pid].computed = comp
        else:
            people.participants[pid] = PersonEntry(
                computed=comp, editable=PersonEditable()
            )

    return people


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------


def write_people_file(people: PeopleFile, output_dir: Path) -> Path:
    """Write ``people.yaml`` to *output_dir*.

    Uses block-style YAML with a human-readable comment header.
    """
    path = output_dir / PEOPLE_FILENAME
    output_dir.mkdir(parents=True, exist_ok=True)

    data = people.model_dump(mode="json")

    yaml_content = yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    path.write_text(_HEADER + yaml_content, encoding="utf-8")
    logger.info("Wrote people file: %s", path)
    return path


# ---------------------------------------------------------------------------
# Display name helper
# ---------------------------------------------------------------------------


def build_display_name_map(people: PeopleFile) -> dict[str, str]:
    """Build a mapping from ``participant_id`` → display name.

    Returns ``short_name`` if set, otherwise ``participant_id``.
    """
    names: dict[str, str] = {}
    for pid, entry in people.participants.items():
        if entry.editable.short_name:
            names[pid] = entry.editable.short_name
        else:
            names[pid] = pid
    return names


# ---------------------------------------------------------------------------
# Name extraction from metadata
# ---------------------------------------------------------------------------

# Labels that are generic placeholders, not real names.
_GENERIC_LABEL_RE = re.compile(
    r"^(speaker\s*[a-z0-9]|SPEAKER_\d+|unknown|narrator)$",
    re.IGNORECASE,
)

# A dial-in caller's label is their phone number, masked or not —
# "+44 7700 ****23", "+1 (555) 010-9876". Teams and Zoom both write these.
# Never a name: it is a digit string, and an unmasked one is PII that would
# otherwise land in people.yaml as somebody's full_name.
_MASKED_PHONE_RE = re.compile(r"^\+?[\d\s()*#•·.\-]{6,}$")


def is_generic_label(label: str) -> bool:
    """Is this speaker label a placeholder rather than a person's name?

    True for Whisper/diarisation placeholders ("Speaker A", "SPEAKER_00",
    "Unknown"), bare numbers, and phone numbers, masked or whole. Every
    surface that turns a label into a name asks this one question — the
    people file, the one-transcript-per-session choice, the splitter gate —
    so a new placeholder shape is added here and nowhere else.
    """
    stripped = label.strip()
    if not stripped:
        return True
    if _GENERIC_LABEL_RE.match(stripped):
        return True
    if stripped.isdigit():
        return True
    if _MASKED_PHONE_RE.match(stripped) and any(ch.isdigit() or ch == "*" for ch in stripped):
        return True
    return False


def extract_names_from_labels(
    transcripts: list[FullTranscript],
    *,
    platform_only: bool = False,
) -> dict[str, str]:
    """Extract probable real names from ``speaker_label`` metadata.

    Teams/VTT transcripts often have real names as speaker labels
    (e.g. "Sarah Jones" instead of "Speaker A").  Returns
    ``{participant_code: name}`` for labels that look like real names —
    keyed by each participant's speaker code when the segments carry one, so
    every named participant in a two-participant session gets a name, not
    only the session's primary one; a transcript without codes keys on its
    ``participant_id`` as before.

    With ``platform_only``, only labels written by a transcript FILE count
    (``PLATFORM_TRANSCRIPT_SOURCES``): the platform's own record of who
    spoke, which ``auto_populate_names`` lets beat the LLM's guess.
    """
    names: dict[str, str] = {}
    for transcript in transcripts:
        # Per participant code, how often each label appears.
        label_counts: dict[str, dict[str, int]] = {}
        for seg in transcript.segments:
            if seg.speaker_role != SpeakerRole.PARTICIPANT or not seg.speaker_label:
                continue
            if platform_only and seg.source not in PLATFORM_TRANSCRIPT_SOURCES:
                continue
            pid = seg.speaker_code or transcript.participant_id
            counts = label_counts.setdefault(pid, {})
            counts[seg.speaker_label] = counts.get(seg.speaker_label, 0) + 1
        for pid, counts in label_counts.items():
            # Pick the most frequent label.
            label = max(counts, key=counts.get)  # type: ignore[arg-type]
            # Skip placeholders, numbers and phone labels.
            if is_generic_label(label):
                continue
            names[pid] = label.strip()
    return names


# ---------------------------------------------------------------------------
# Auto-populate editable fields from extracted data
# ---------------------------------------------------------------------------


def auto_populate_names(
    people: PeopleFile,
    speaker_infos: dict[str, SpeakerInfo],
    label_names: dict[str, str],
    *,
    platform_names: dict[str, str] | None = None,
) -> None:
    """Pre-populate empty ``full_name``/``role`` fields from extracted data.

    Only fills fields that are currently empty — never overwrites user edits.
    Priority: platform-transcript name > LLM-extracted name > other label.

    ``platform_names`` is what the platform itself wrote against each
    participant's turns (``extract_names_from_labels(..., platform_only=True)``).
    It is the one source that is not a guess, so it beats the LLM's
    ``person_name`` — measured on the Talismanic study, the model's "Pri" had
    been overwriting Teams' own "Priya Nair". Participants only: moderators
    are not named from labels in this slice (every session's moderator is
    ``m1``, so the last session processed would win — see
    ``docs/design-cloud-import-transcripts.md`` §0b). ``label_names`` keeps
    its old place for labels of unknown provenance, so the LLM still beats a
    generic label.

    For a shared moderator code the ``speaker_infos`` entry is whichever
    session the caller iterated last (``pipeline.py``, the ``pid_speaker_info``
    loop), including one whose ``person_name`` is empty — so the name on
    ``m1`` is an accident of session order (storyboard frame F2).  Under route
    C (``docs/design-people.md`` §E decision 1, corrected 1 Oct 2026) an LLM
    hearing becomes a hint on an unidentified slot and never fills a name;
    only a platform label proposes one.  The never-overwrite rule survives as
    "never touch a confirmed row".

    Mutates *people* in place.
    """
    platform_names = platform_names or {}
    for pid, entry in people.participants.items():
        ed = entry.editable

        # full_name: platform label (participants) > LLM > other label metadata
        if not ed.full_name:
            info = speaker_infos.get(pid)
            if pid.startswith("p") and pid in platform_names:
                ed.full_name = platform_names[pid]
            elif info and info.person_name:
                ed.full_name = info.person_name
            elif pid in label_names:
                ed.full_name = label_names[pid]

        # role (job title): LLM only
        if not ed.role:
            info = speaker_infos.get(pid)
            if info and info.job_title:
                ed.role = info.job_title


# ---------------------------------------------------------------------------
# Short name suggestion
# ---------------------------------------------------------------------------


def _extract_given_name(full_name: str) -> str:
    """Extract the likely given name from a full name.

    Handles three special cases using pre-loaded data files:

    1. **CJK ideographic names** (Chinese/Japanese/Korean characters without
       spaces) — the full name is already short enough, returned as-is.
    2. **Honorific prefixes** ("Dr.", "Prof.", etc.) — stripped before
       extracting the first token.
    3. **Family-name-first cultures** (Chinese, Korean, Vietnamese, Japanese,
       Hungarian) — when the first token matches a known family name, the
       *second* token is returned instead.

    Falls back to the first whitespace-delimited token for all other names.
    """
    # CJK names without spaces are already short — use as-is.
    if _CJK_RE.search(full_name) and " " not in full_name:
        return full_name

    # Strip honorific prefix ("Dr. Sarah Jones" → "Sarah Jones").
    stripped = _strip_honorific(full_name)
    parts = stripped.split()
    if not parts:
        return full_name

    # Family-name-first detection: if the first token is a known family
    # name from a family-first culture, take the second token (the given
    # name) instead.
    if len(parts) >= 2 and parts[0].lower() in _FAMILY_FIRST_SURNAMES:
        return parts[1]

    return parts[0]


def suggest_short_names(people: PeopleFile) -> None:
    """Auto-suggest ``short_name`` for participants missing one.

    Extracts the likely given name from ``full_name``, handling honorifics,
    CJK names, and family-name-first conventions.  When two participants
    share a given name, disambiguates with the last-name initial
    (e.g. "Sarah J." vs "Sarah K.").

    Only sets ``short_name`` on entries where it is currently empty.
    Mutates *people* in place.
    """
    # Collect candidates: entries that have full_name but no short_name.
    candidates: dict[str, str] = {}  # pid -> given_name
    for pid, entry in people.participants.items():
        if entry.editable.full_name and not entry.editable.short_name:
            candidates[pid] = _extract_given_name(entry.editable.full_name)

    if not candidates:
        return

    # Detect given-name collisions.
    first_counts: dict[str, int] = {}
    for given in candidates.values():
        first_counts[given] = first_counts.get(given, 0) + 1

    # Assign short names.
    for pid, given in candidates.items():
        if first_counts[given] > 1:
            # Disambiguate: append last-name initial if available.
            parts = people.participants[pid].editable.full_name.split()
            if len(parts) >= 2:
                short = f"{given} {parts[-1][0]}."
            else:
                short = given
        else:
            short = given
        people.participants[pid].editable.short_name = short


# ---------------------------------------------------------------------------
# Per-session moderator and observer names
# ---------------------------------------------------------------------------
#
# Moderator and observer codes restart in every session (``m1`` is "the first
# moderator *in this session*"), so ``people.yaml``, keyed by code, can hold
# only one name for all of them — the last session processed wins. The serve
# DB already keeps one speaker row per (session, code); this file is what lets
# it name each one from its own session. Participants are not in it: their
# codes are study-wide and ``people.yaml`` names them correctly.
#
# A step towards route C (``docs/design-people.md`` §H H9), not route C itself:
# no identities, no ``m?``. Decided by the owner on 3 Oct 2026 as the weekend
# fix; the identity layer builds on the per-session rows this fills.

SESSION_SPEAKERS_FILENAME = "session-speakers.json"
SESSION_SPEAKERS_VERSION = 2
#: Versions ``load_session_speakers`` reads. Version 1 recorded no evidence
#: class, so its names arrive as ``inherited`` proposals.
_SESSION_SPEAKERS_READABLE = (1, 2)


def session_speakers_path(output_dir: Path) -> Path:
    return output_dir / ".bristlenose" / "intermediate" / SESSION_SPEAKERS_FILENAME


def session_speaker_names(
    transcripts: list[FullTranscript],
    speaker_infos: dict[str, list[SpeakerInfo]],
    label_codes: dict[str, dict[str, str]],
) -> dict[str, dict[str, dict[str, str]]]:
    """Name each session's moderators and observers from that session alone.

    Returns ``{session_id: {code: {"full_name", "short_name", "role",
    "evidence"}}}`` for ``m*``/``o*`` codes. The precedence is the
    participants' one (``auto_populate_names``): the label a platform
    transcript wrote, then the LLM's ``person_name`` for that speaker in *this*
    session, then any label that is not a placeholder. ``role`` is the LLM's
    job title. ``evidence`` says which of the three named it —
    ``platform-name``, ``heard`` or ``label`` — so the importer can weigh a
    platform's record against a model's hearing (route C,
    ``docs/design-people.md`` §C5); it is ``""`` when only a job title was
    found.
    """
    result: dict[str, dict[str, dict[str, str]]] = {}
    for transcript in transcripts:
        sid = transcript.session_id
        # Per code: label counts, and which labels a platform wrote.
        counts: dict[str, dict[str, int]] = {}
        platform: dict[str, set[str]] = {}
        for seg in transcript.segments:
            code = seg.speaker_code
            if not code or code[0] not in "mo" or not seg.speaker_label:
                continue
            c = counts.setdefault(code, {})
            c[seg.speaker_label] = c.get(seg.speaker_label, 0) + 1
            if seg.source in PLATFORM_TRANSCRIPT_SOURCES:
                platform.setdefault(code, set()).add(seg.speaker_label)

        codes_for_label = label_codes.get(sid, {})
        llm: dict[str, SpeakerInfo] = {}
        for info in speaker_infos.get(sid, []):
            code = codes_for_label.get(info.speaker_label, "")
            if code and code[0] in "mo":
                llm[code] = info

        names: dict[str, dict[str, str]] = {}
        for code in sorted(set(counts) | set(llm)):
            label = max(counts[code], key=counts[code].get) if code in counts else ""  # type: ignore[arg-type]
            real_label = "" if is_generic_label(label) else label.strip()
            info = llm.get(code)
            if real_label and real_label in platform.get(code, set()):
                full_name, evidence = real_label, "platform-name"
            elif info and info.person_name:
                full_name, evidence = info.person_name, "heard"
            else:
                full_name, evidence = real_label, "label"
            role = info.job_title if info and info.job_title else ""
            if not full_name and not role:
                continue
            names[code] = {
                "full_name": full_name,
                "short_name": _extract_given_name(full_name) if full_name else "",
                "role": role,
                "evidence": evidence if full_name else "",
            }
        if names:
            result[sid] = names
    return result


def session_speaker_stats(
    sessions: list[InputSession],
    transcripts: list[FullTranscript],
) -> dict[str, dict[str, dict[str, object]]]:
    """Each session's speakers' stats, keyed by session then speaker code.

    ``compute_participant_stats`` keys by code alone, so every session's ``m1``
    lands on one entry; this keeps them apart, for the serve DB's
    ``session_speakers`` rows. ``pct_words`` is a participant's share of every
    participant's words in the study (moderators and observers get 0.0, as
    there); ``pct_time_speaking`` is the share of that session's duration.
    """
    by_sid = {t.session_id: t for t in transcripts}
    result: dict[str, dict[str, dict[str, object]]] = {}
    participant_words = 0
    participants: list[tuple[dict[str, object], int]] = []
    for session in sessions:
        transcript = by_sid.get(session.session_id)
        if transcript is None:
            continue
        words: dict[str, int] = {}
        seconds: dict[str, float] = {}
        for seg in transcript.segments:
            code = seg.speaker_code or session.participant_id
            words[code] = words.get(code, 0) + len(seg.text.split())
            seconds[code] = seconds.get(code, 0.0) + max(0.0, seg.end_time - seg.start_time)
        per: dict[str, dict[str, object]] = {}
        for code, count in words.items():
            duration = transcript.duration_seconds
            per[code] = {
                "words_spoken": count,
                "pct_words": 0.0,
                "pct_time_speaking": (
                    round(seconds[code] / duration * 100, 1) if duration > 0 else 0.0
                ),
                "source_file": transcript.source_file,
            }
            if code.startswith("p"):
                participant_words += count
                participants.append((per[code], count))
        result[session.session_id] = per
    if participant_words:
        for entry, count in participants:
            entry["pct_words"] = round(count / participant_words * 100, 1)
    return result


def write_session_speakers(
    names: dict[str, dict[str, dict[str, str]]],
    output_dir: Path,
    stats: dict[str, dict[str, dict[str, object]]] | None = None,
) -> Path:
    """Write the per-session names and stats atomically (they are names: kept
    hidden)."""
    import json
    import os
    import tempfile

    path = session_speakers_path(output_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, object] = {"version": SESSION_SPEAKERS_VERSION, "sessions": names}
    if stats is not None:
        payload["stats"] = stats
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".session-speakers.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return path


def _read_session_speakers(output_dir: Path) -> dict[str, object] | None:
    import json

    path = session_speakers_path(output_dir)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        logger.warning("Could not read %s; moderators are left unidentified", path)
        return None
    if not isinstance(data, dict) or data.get("version") not in _SESSION_SPEAKERS_READABLE:
        logger.warning("Unexpected format in %s; moderators are left unidentified", path)
        return None
    return data


def load_session_speakers(output_dir: Path) -> dict[str, dict[str, dict[str, str]]] | None:
    """Read the per-session moderator and observer names, or ``None`` if the
    project has not been re-run since they were introduced.

    Every entry carries ``evidence``; a version-1 file, which recorded none,
    reads as ``inherited``.
    """
    data = _read_session_speakers(output_dir)
    if data is None:
        return None
    sessions = data.get("sessions")
    if not isinstance(sessions, dict):
        return None
    if data.get("version") == 1:
        for per in sessions.values():
            for entry in per.values():
                if entry.get("full_name"):
                    entry.setdefault("evidence", "inherited")
    return sessions


def load_session_speaker_stats(
    output_dir: Path,
) -> dict[str, dict[str, dict[str, object]]]:
    """Read the per-session speaker stats; ``{}`` when the file has none."""
    data = _read_session_speakers(output_dir)
    stats = data.get("stats") if data else None
    return stats if isinstance(stats, dict) else {}
