#!/usr/bin/env bash
# Download FOSSDA (Free and Open Source Stories Digital Archive) interviews.
#
# Reads signed S3 URLs from a manifest file and downloads MP4s with curl.
# The manifest is generated by visiting each Aviary page and extracting the
# video source URL (Cloudflare blocks automated scraping, so URLs must be
# extracted via a browser — see REFRESH INSTRUCTIONS below).
#
# Usage:
#   ./scripts/download-fossda.sh                    # download all
#   ./scripts/download-fossda.sh --dry-run          # show what would be downloaded
#   ./scripts/download-fossda.sh --skip-existing    # skip already-downloaded files
#
# Output: trial-runs/fossda-opensource/*.mp4

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/trial-runs/fossda-opensource"
MANIFEST="$REPO_ROOT/trial-runs/fossda-opensource/manifest.json"

DRY_RUN=false
SKIP_EXISTING=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --skip-existing) SKIP_EXISTING=true ;;
    *) echo "Unknown arg: $arg"; exit 1 ;;
  esac
done

if [ ! -f "$MANIFEST" ]; then
  echo "ERROR: Manifest not found at $MANIFEST"
  echo ""
  echo "Generate it by running the browser console snippet — see comments in this script."
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo ""
echo "FOSSDA Download Script"
echo "Output:  $OUTPUT_DIR"
echo "Options: $([ "$DRY_RUN" = true ] && echo 'DRY RUN' || echo 'live'), $([ "$SKIP_EXISTING" = true ] && echo 'skip existing' || echo 'overwrite')"
echo ""

# Parse manifest with python (available in .venv)
ENTRIES=$("$REPO_ROOT/.venv/bin/python3" -c "
import json, sys
with open('$MANIFEST') as f:
    data = json.load(f)
for entry in data:
    slug = entry['slug']
    url = entry['videoUrl']
    dur = entry.get('durationSec', 0)
    mins = int(float(dur) / 60)
    print(f'{slug}\t{mins}m\t{url}')
")

OK=0
SKIPPED=0
FAILED=0

while IFS=$'\t' read -r slug duration url; do
  dest="$OUTPUT_DIR/${slug}.mp4"
  echo "── ${slug} (${duration}) ──"

  if [ "$SKIP_EXISTING" = true ] && [ -f "$dest" ] && [ -s "$dest" ]; then
    echo "   Skipped (exists: $(du -h "$dest" | cut -f1))"
    echo ""
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  if [ "$DRY_RUN" = true ]; then
    echo "   URL: ${url:0:80}..."
    echo "   [dry run — not downloading]"
    echo ""
    continue
  fi

  echo "   Downloading..."
  if curl -fSL -C - -o "$dest" "$url" 2>&1; then
    SIZE=$(du -h "$dest" | cut -f1)
    echo "   Done ($SIZE)"
    OK=$((OK + 1))
  else
    echo "   FAILED (curl exit $?)"
    FAILED=$((FAILED + 1))
    # Remove partial file
    rm -f "$dest"
  fi
  echo ""
done <<< "$ENTRIES"

echo "════════════════════════════════════════════════════════"
echo "SUMMARY: $OK downloaded, $SKIPPED skipped, $FAILED failed"
echo "Output:  $OUTPUT_DIR"
echo ""

if [ "$FAILED" -gt 0 ]; then
  echo "Some downloads failed. The signed URLs may have expired."
  echo "Re-generate manifest.json — see instructions below."
  echo ""
fi

# ── REFRESH INSTRUCTIONS ──────────────────────────────────────────────────
#
# Signed S3 URLs expire after ~80 minutes. If downloads fail with 403,
# regenerate the manifest:
#
# 1. Open each Aviary page in your browser (list below)
# 2. Open DevTools console (Cmd+Option+J)
# 3. Paste this snippet:
#
#    copy(JSON.stringify({
#      slug: document.title.split('|')[0].trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-+$/,''),
#      videoUrl: document.querySelector('video source')?.src,
#      durationSec: window.create_clip?.end_time
#    }))
#
# 4. Paste into a text file, one JSON object per line
# 5. Wrap in array brackets: [ {line1}, {line2}, ... ]
# 6. Save as trial-runs/fossda-opensource/manifest.json
#
# Pages:
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/55142
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/106637
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/92612
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/56969
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/106636
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/86317
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/86318
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/85901
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/55141
#   https://fossda.aviaryplatform.com/collections/1633/collection_resources/55140
