import Foundation

/// Compact provenance line for screenshots, support bundles, and the in-app
/// diagnostic footer.
///
/// Combines version (from Info.plist), git branch + SHA + dirty flag (from
/// `GeneratedBuildInfo`, regenerated by `desktop/scripts/generate-build-info.sh`
/// before every compile), build configuration, sandbox / Hardened Runtime
/// state, and the resolved sidecar mode.
///
/// Example one-line summary:
/// `v0.15.0 · track-c-c1-bundled-sidecar · d886938 · Release · sandbox=off HR=off · sidecar=bundled`
///
/// Visibility:
/// - Footer overlay in `ContentView`: `#if DEBUG` only (never in TestFlight /
///   App Store builds — the line leaks branch names and looks unprofessional
///   to end users).
/// - About menu "Build Info…" sheet: always visible, copyable.
/// - `os.Logger` line at app launch: always emitted to Console.app, helping
///   archaeology when a user posts a screenshot of the *app* without the
///   diagnostic line visible.
struct BuildInfo {
    let appVersion: String
    let buildNumber: String
    let gitBranch: String
    /// Short SHA, with `-dirty` suffix when the working tree had uncommitted
    /// changes at build time.
    let gitSHA: String
    let configuration: String
    let sandboxEnabled: Bool
    let hardenedRuntimeEnabled: Bool
    let buildDate: String

    /// Snapshot of build-time-known facts. Sidecar mode is added by the
    /// caller (it's resolved at runtime by `ServeManager`).
    static let current = BuildInfo()

    private init() {
        let info = Bundle.main.infoDictionary
        self.appVersion = info?["CFBundleShortVersionString"] as? String ?? "?"
        self.buildNumber = info?["CFBundleVersion"] as? String ?? "?"
        self.gitBranch = GeneratedBuildInfo.gitBranch
        self.gitSHA = GeneratedBuildInfo.gitDirty
            ? "\(GeneratedBuildInfo.gitSHA)-dirty"
            : GeneratedBuildInfo.gitSHA
        self.configuration = GeneratedBuildInfo.configuration
        self.sandboxEnabled = GeneratedBuildInfo.sandboxEnabled
        self.hardenedRuntimeEnabled = GeneratedBuildInfo.hardenedRuntimeEnabled
        self.buildDate = GeneratedBuildInfo.buildDate
    }

    /// One-line summary, target format spec'd in the C1 closeout note.
    func oneLine(sidecar: String) -> String {
        let sandbox = sandboxEnabled ? "on" : "off"
        let hr = hardenedRuntimeEnabled ? "on" : "off"
        return "v\(appVersion) · \(gitBranch) · \(gitSHA) · \(configuration) · sandbox=\(sandbox) HR=\(hr) · sidecar=\(sidecar)"
    }

    /// Multi-line block for the About > Build Info sheet — same data plus
    /// build number and build date for support-bundle paste-ability.
    func detailed(sidecar: String) -> String {
        """
        Bristlenose \(appVersion) (\(buildNumber))
        Branch:        \(gitBranch)
        Commit:        \(gitSHA)
        Configuration: \(configuration)
        Sandbox:       \(sandboxEnabled ? "on" : "off")
        Hardened RT:   \(hardenedRuntimeEnabled ? "on" : "off")
        Sidecar:       \(sidecar)
        Built:         \(buildDate)
        """
    }
}
