// Generated by desktop/scripts/generate-build-info.sh — do not edit.
// Regenerated by Xcode Run Script Build Phase before every compile.
import Foundation

enum GeneratedBuildInfo {
    static let gitBranch = "pipeline-diagnostic-popover-swift"
    static let gitSHA = "04b86ee"
    static let gitDirty = true
    static let configuration = "Debug"
    static let sandboxEnabled = true
    static let hardenedRuntimeEnabled = false
    static let buildDate = "2026-05-19T12:04:04Z"
}
