// Generated by desktop/scripts/generate-build-info.sh — do not edit.
// Regenerated by Xcode Run Script Build Phase before every compile.
import Foundation

enum GeneratedBuildInfo {
    static let gitBranch = "main"
    static let gitSHA = "bf272cc"
    static let gitDirty = true
    static let configuration = "Debug"
    static let sandboxEnabled = true
    static let hardenedRuntimeEnabled = false
    static let buildDate = "2026-05-19T16:13:52Z"
}
