// Generated by desktop/scripts/generate-build-info.sh — do not edit.
// Regenerated by Xcode Run Script Build Phase before every compile.
//
// This stub is committed to git so that PBXFileSystemSynchronizedRootGroup
// picks up the file at project-load time. Local builds will overwrite the
// stub with real git/build values; `cmp -s` in the generator skips writes
// when contents match, so committed branches stay clean for unrelated work.
import Foundation

enum GeneratedBuildInfo {
    static let gitBranch = "unknown"
    static let gitSHA = "unknown"
    static let gitDirty = false
    static let configuration = "Debug"
    static let sandboxEnabled = false
    static let hardenedRuntimeEnabled = false
    static let buildDate = "1970-01-01T00:00:00Z"
}
