# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the bristlenose desktop sidecar (Track C).
#
# Per docs/design-modularity.md:
#   - Mac is MLX-only (ctranslate2 + faster-whisper excluded)
#   - Presidio + spaCy excluded (Background Assets post-alpha)
#   - Keeps mlx + mlx_whisper (Apple Silicon transcription)
#
# Usage (via desktop/scripts/build-sidecar.sh):
#   cd <repo-root>
#   .venv/bin/python -m PyInstaller \
#       --distpath desktop/Bristlenose/Resources \
#       --workpath desktop/build/pyinstaller \
#       --clean --noconfirm \
#       desktop/bristlenose-sidecar.spec

import os

from PyInstaller.utils.hooks import collect_all, collect_submodules

PROJECT_ROOT = os.path.abspath(os.path.join(SPECPATH, ".."))

# PyInstaller's default analysis walks `import mlx.core` and copies
# core.cpython-312-darwin.so + libmlx.dylib, but misses libjaccl.dylib
# (linked by libmlx via @rpath), mlx.metallib (the compiled Metal shader
# library libmlx loads at first kernel dispatch), and a handful of small
# pure-python submodules that mlx's native init probes (`mlx.nn`,
# `mlx.optimizers`, `mlx.utils`, `mlx._distributed_utils`, etc.). Without
# all of them `import mlx_whisper` fails inside the bundled sidecar with
# either `Library not loaded: @rpath/libjaccl.dylib` or the more
# inscrutable nanobind `Encountered an error while initializing the
# extension.` Discovered during S3 bundle-trim (4 May 2026): pre-existing
# latent bug exposed by trimming torch, which had been masking the
# breakage by being the first thing to fail in the import chain.
# `collect_all` mirrors `pip install`'s view of the package, which is
# what mlx_metal's wheel layout assumes at runtime.
_MLX_DATAS, _MLX_BINARIES, _MLX_HIDDEN = collect_all("mlx")

a = Analysis(
    # Entry point: run `bristlenose serve` directly.
    [os.path.join(SPECPATH, "sidecar_entry.py")],
    pathex=[PROJECT_ROOT],
    binaries=_MLX_BINARIES,
    datas=[
        *_MLX_DATAS,
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "theme"),
            os.path.join("bristlenose", "theme"),
        ),
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "data"),
            os.path.join("bristlenose", "data"),
        ),
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "locales"),
            os.path.join("bristlenose", "locales"),
        ),
        # LLM prompt templates (.md files loaded at runtime by
        # bristlenose/llm/prompts/__init__.py::_load_prompt). Every
        # LLM-using stage reads from here — topic-segmentation,
        # quote-extraction, thematic-grouping, autocode, etc.
        # Without this entry, every LLM call fails with FileNotFoundError
        # before reaching the provider (BUG-5 from the C3 smoke test,
        # 21 Apr 2026).
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "llm", "prompts"),
            os.path.join("bristlenose", "llm", "prompts"),
        ),
        # Cohort baselines for LLM cost forecasting (bristlenose/llm/pricing.py
        # ::_load_baselines reads at runtime). Falls back to empty list on
        # missing file, but cost-forecast quality degrades — ship the file.
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "llm", "cohort-baselines.json"),
            os.path.join("bristlenose", "llm"),
        ),
        # Alembic migrations (read at runtime by server/db.py).
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "server", "alembic"),
            os.path.join("bristlenose", "server", "alembic"),
        ),
        # React SPA build output. Generated by `cd frontend && npm run build`,
        # gitignored at the source. PyInstaller will fail loudly if this
        # directory is missing — that's intentional, the build script must
        # ensure the React bundle is present before sidecar packaging.
        # Without this entry the sidecar serves the deprecated static-render
        # HTML for everything (BUG-3 from the C3 smoke test, 21 Apr 2026).
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "server", "static"),
            os.path.join("bristlenose", "server", "static"),
        ),
        # YAML codebook templates (garrett, morville, norman, uxr, plato).
        # Loaded by routes/codebook.py and exposed via the Browse Codebooks
        # modal. Without this entry the CODEBOOK FRAMEWORKS list is empty
        # (BUG-4 from the C3 smoke test, 21 Apr 2026).
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "server", "codebook"),
            os.path.join("bristlenose", "server", "codebook"),
        ),
        # LLM cost-baselines (alpha-telemetry Slice A, 27 Apr 2026).
        # bristlenose/llm/pricing.py:68 loads this at runtime via
        # `Path(__file__).parent / "cohort-baselines.json"` for the
        # baseline-fallback path of cost forecasting. Without this entry
        # the sidecar can't resolve baselines and falls back to whatever
        # the no-baseline path does — silent in unit tests because they
        # run against `pip install -e .` where __file__ resolves correctly.
        (
            os.path.join(PROJECT_ROOT, "bristlenose", "llm", "cohort-baselines.json"),
            os.path.join("bristlenose", "llm"),
        ),
    ],
    hiddenimports=[
        *_MLX_HIDDEN,
        *collect_submodules("rich"),
        # LLM providers (dynamically imported in llm/client.py)
        "anthropic",
        "openai",
        "google.genai",
        "google.genai.types",
        # MLX only — no ctranslate2/faster-whisper in the sidecar.
        "mlx",
        "mlx_whisper",
        # Serve mode
        "fastapi",
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "sqlalchemy",
        "sqlalchemy.dialects.sqlite",
        "sqladmin",
        # Bristlenose lazy imports
        "bristlenose.server",
        "bristlenose.server.app",
        "bristlenose.server.db",
        "bristlenose.server.models",
        "bristlenose.server.importer",
        "bristlenose.server.admin",
        "bristlenose.server.routes",
        "bristlenose.server.routes.codebook",
        "bristlenose.server.routes.dashboard",
        "bristlenose.server.routes.data",
        "bristlenose.server.routes.dev",
        "bristlenose.server.routes.health",
        "bristlenose.server.routes.quotes",
        "bristlenose.server.routes.sessions",
        "bristlenose.server.routes.transcript",
        "bristlenose.ollama",
        "bristlenose.providers",
        "bristlenose.credentials_macos",
        "bristlenose.analysis",
        "bristlenose.analysis.matrix",
        "bristlenose.analysis.signals",
        "bristlenose.analysis.metrics",
        "bristlenose.analysis.models",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Explicitly excluded per design-modularity.md.
        "ctranslate2",
        "faster_whisper",
        "presidio_analyzer",
        "presidio_anonymizer",
        "spacy",
        "en_core_web_lg",
        # Orphan checkpoint-conversion tool inside mlx_whisper. Top-level
        # `import torch` pulls ~284 MB of torch into the bundle, but nothing
        # in mlx_whisper (or anywhere else) actually imports torch_whisper —
        # it's a dev utility for converting OpenAI Whisper checkpoints to
        # MLX format. Excluding it sheds torch entirely. Verified orphan via
        # `grep -rn torch_whisper site-packages/mlx_whisper/` (4 May 2026).
        "mlx_whisper.torch_whisper",
        # S3 step 1: huggingface_hub.serialization._torch does `import torch`
        # at top level. mlx_whisper only uses huggingface_hub.snapshot_download
        # for model HTTP fetches — verified in load_models.py — so the torch-
        # serialisation submodule is dead weight. Removing it kills one of the
        # four torch-import edges PyInstaller's modulegraph follows.
        "huggingface_hub.serialization._torch",
        # huggingface_hub.hub_mixin defines a PyTorchModelHubMixin that does
        # `import torch` at top level. mlx_whisper doesn't use the mixin
        # (only snapshot_download), so it's another dead torch caller.
        "huggingface_hub.hub_mixin",
        # S3 step 2: scipy probes torch on import via the array-API-compat
        # shim. mlx_whisper doesn't ask scipy to operate on torch tensors
        # (it uses MLX arrays exclusively), so the whole .torch subpackage
        # is dead under our usage. Keeps the rest of scipy intact.
        "scipy._lib.array_api_compat.torch",
        # S3 step 3: onnxruntime is reached via faster_whisper.vad and via
        # torch.onnx._internal.exporter. Both upstreams are excluded /
        # unused on Mac (faster_whisper already in excludes; torch is MLX-
        # alternative-path, not us). Dropping the whole package sheds 58 MB
        # AND removes onnxruntime.transformers.machine_info from torch's
        # incoming-edge list.
        "onnxruntime",
        # S3 step 4: torch (288 MB) — the headline trim. After steps 1–3
        # the only remaining torch importers in the modulegraph are
        # functorch.* (torch's own internal cycle, gone with torch) and
        # scipy._lib.array_api_compat.common._helpers (a generic helper
        # that probes torch via try/except — safe under MLX-only). Mac
        # transcription path is MLX (mlx_whisper); torch has no load-
        # bearing role at runtime per design-modularity.md "Mac is
        # MLX-only".
        "torch",
        "torchgen",
        "torchvision",
        "functorch",
        "pytest",
        "pytest_cov",
        "pytest_asyncio",
        "ruff",
        "mypy",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="bristlenose-sidecar",
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,
    console=True,
    target_arch="arm64",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=True,
    upx=False,
    name="bristlenose-sidecar",
)
